// Generated by protocol_builder
// Do not edit

package _338

import (
	"github.com/ShadowJonathan/mopher/Protocol/lib"
	"io"
	"io/ioutil"
	"math"
)

func (t *TeleConfirm) Id() int { return 0 }
func (t *TeleConfirm) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, t.ID); err != nil {
		return
	}
	return
}
func (t *TeleConfirm) Read(rr io.Reader) (err error) {
	if t.ID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (t *TabComplete) Id() int { return 1 }
func (t *TabComplete) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	if err = lib.WriteString(ww, t.Text); err != nil {
		return
	}
	if err = lib.WriteBool(ww, t.HasTarget); err != nil {
		return
	}
	if t.HasTarget == true {
		tmp[0] = byte(t.Target >> 56)
		tmp[1] = byte(t.Target >> 48)
		tmp[2] = byte(t.Target >> 40)
		tmp[3] = byte(t.Target >> 32)
		tmp[4] = byte(t.Target >> 24)
		tmp[5] = byte(t.Target >> 16)
		tmp[6] = byte(t.Target >> 8)
		tmp[7] = byte(t.Target >> 0)
		if _, err = ww.Write(tmp[:8]); err != nil {
			return
		}
	}
	return
}
func (t *TabComplete) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	if t.Text, err = lib.ReadString(rr); err != nil {
		return
	}
	if t.HasTarget, err = lib.ReadBool(rr); err != nil {
		return
	}
	if t.HasTarget == true {
		if _, err = rr.Read(tmp[:8]); err != nil {
			return
		}
		t.Target = (lib.Position(tmp[7]) << 0) | (lib.Position(tmp[6]) << 8) | (lib.Position(tmp[5]) << 16) | (lib.Position(tmp[4]) << 24) | (lib.Position(tmp[3]) << 32) | (lib.Position(tmp[2]) << 40) | (lib.Position(tmp[1]) << 48) | (lib.Position(tmp[0]) << 56)
	}
	return
}

func (c *ChatMessage) Id() int { return 2 }
func (c *ChatMessage) Write(ww io.Writer) (err error) {
	if err = lib.WriteString(ww, c.Message); err != nil {
		return
	}
	return
}
func (c *ChatMessage) Read(rr io.Reader) (err error) {
	if c.Message, err = lib.ReadString(rr); err != nil {
		return
	}
	return
}

func (c *ClientStatus) Id() int { return 3 }
func (c *ClientStatus) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, c.ActionID); err != nil {
		return
	}
	return
}
func (c *ClientStatus) Read(rr io.Reader) (err error) {
	if c.ActionID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (c *ClientSettings) Id() int { return 4 }
func (c *ClientSettings) Write(ww io.Writer) (err error) {
	var tmp [1]byte
	if err = lib.WriteString(ww, c.Locale); err != nil {
		return
	}
	tmp[0] = byte(c.ViewDistance >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(c.ChatMode >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	if err = lib.WriteBool(ww, c.ChatColors); err != nil {
		return
	}
	tmp[0] = byte(c.DisplayedSkinParts >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, c.MainHand); err != nil {
		return
	}
	return
}
func (c *ClientSettings) Read(rr io.Reader) (err error) {
	var tmp [1]byte
	if c.Locale, err = lib.ReadString(rr); err != nil {
		return
	}
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.ViewDistance = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.ChatMode = (byte(tmp[0]) << 0)
	if c.ChatColors, err = lib.ReadBool(rr); err != nil {
		return
	}
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.DisplayedSkinParts = (byte(tmp[0]) << 0)
	if c.MainHand, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (c *ConfirmTransactionServerbound) Id() int { return 5 }
func (c *ConfirmTransactionServerbound) Write(ww io.Writer) (err error) {
	var tmp [2]byte
	tmp[0] = byte(c.ID >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(c.ActionNumber >> 8)
	tmp[1] = byte(c.ActionNumber >> 0)
	if _, err = ww.Write(tmp[:2]); err != nil {
		return
	}
	if err = lib.WriteBool(ww, c.Accepted); err != nil {
		return
	}
	return
}
func (c *ConfirmTransactionServerbound) Read(rr io.Reader) (err error) {
	var tmp [2]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.ID = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:2]); err != nil {
		return
	}
	c.ActionNumber = int16((uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8))
	if c.Accepted, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (e *EnchantItem) Id() int { return 6 }
func (e *EnchantItem) Write(ww io.Writer) (err error) {
	var tmp [1]byte
	tmp[0] = byte(e.ID >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(e.Enchantment >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	return
}
func (e *EnchantItem) Read(rr io.Reader) (err error) {
	var tmp [1]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	e.ID = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	e.Enchantment = (byte(tmp[0]) << 0)
	return
}

func (c *ClickWindow) Id() int { return 7 }
func (c *ClickWindow) Write(ww io.Writer) (err error) {
	var tmp [2]byte
	tmp[0] = byte(c.ID >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(c.Slot >> 8)
	tmp[1] = byte(c.Slot >> 0)
	if _, err = ww.Write(tmp[:2]); err != nil {
		return
	}
	tmp[0] = byte(c.Button >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(c.ActionNumber >> 8)
	tmp[1] = byte(c.ActionNumber >> 0)
	if _, err = ww.Write(tmp[:2]); err != nil {
		return
	}
	tmp[0] = byte(c.Mode >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	if err = c.ClickedItem.Serialize(ww); err != nil {
		return
	}
	return
}
func (c *ClickWindow) Read(rr io.Reader) (err error) {
	var tmp [2]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.ID = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:2]); err != nil {
		return
	}
	c.Slot = int16((uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8))
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.Button = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:2]); err != nil {
		return
	}
	c.ActionNumber = int16((uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8))
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.Mode = (byte(tmp[0]) << 0)
	if err = c.ClickedItem.Deserialize(rr); err != nil {
		return
	}
	return
}

func (c *CloseWindow) Id() int { return 8 }
func (c *CloseWindow) Write(ww io.Writer) (err error) {
	var tmp [1]byte
	tmp[0] = byte(c.ID >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	return
}
func (c *CloseWindow) Read(rr io.Reader) (err error) {
	var tmp [1]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.ID = (byte(tmp[0]) << 0)
	return
}

func (p *PluginMessageServerbound) Id() int { return 9 }
func (p *PluginMessageServerbound) Write(ww io.Writer) (err error) {
	if err = lib.WriteString(ww, p.Channel); err != nil {
		return
	}
	if _, err = ww.Write(p.Data); err != nil {
		return
	}
	return
}
func (p *PluginMessageServerbound) Read(rr io.Reader) (err error) {
	if p.Channel, err = lib.ReadString(rr); err != nil {
		return
	}
	if p.Data, err = ioutil.ReadAll(rr); err != nil {
		return
	}
	return
}

func (u *UseEntity) Id() int { return 10 }
func (u *UseEntity) Write(ww io.Writer) (err error) {
	var tmp [4]byte
	if err = lib.WriteVarInt(ww, u.TargetID); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, u.Type); err != nil {
		return
	}
	if u.Type == 2 {
		tmp0 := math.Float32bits(u.TargetX)
		tmp[0] = byte(tmp0 >> 24)
		tmp[1] = byte(tmp0 >> 16)
		tmp[2] = byte(tmp0 >> 8)
		tmp[3] = byte(tmp0 >> 0)
		if _, err = ww.Write(tmp[:4]); err != nil {
			return
		}
		tmp1 := math.Float32bits(u.TargetY)
		tmp[0] = byte(tmp1 >> 24)
		tmp[1] = byte(tmp1 >> 16)
		tmp[2] = byte(tmp1 >> 8)
		tmp[3] = byte(tmp1 >> 0)
		if _, err = ww.Write(tmp[:4]); err != nil {
			return
		}
		tmp2 := math.Float32bits(u.TargetZ)
		tmp[0] = byte(tmp2 >> 24)
		tmp[1] = byte(tmp2 >> 16)
		tmp[2] = byte(tmp2 >> 8)
		tmp[3] = byte(tmp2 >> 0)
		if _, err = ww.Write(tmp[:4]); err != nil {
			return
		}
	}
	if u.Type == 0 || u.Type == 2 {
		if err = lib.WriteVarInt(ww, u.Hand); err != nil {
			return
		}
	}
	return
}
func (u *UseEntity) Read(rr io.Reader) (err error) {
	var tmp [4]byte
	if u.TargetID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if u.Type, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if u.Type == 2 {
		var tmp0 uint32
		if _, err = rr.Read(tmp[:4]); err != nil {
			return
		}
		tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
		u.TargetX = math.Float32frombits(tmp0)
		var tmp1 uint32
		if _, err = rr.Read(tmp[:4]); err != nil {
			return
		}
		tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
		u.TargetY = math.Float32frombits(tmp1)
		var tmp2 uint32
		if _, err = rr.Read(tmp[:4]); err != nil {
			return
		}
		tmp2 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
		u.TargetZ = math.Float32frombits(tmp2)
	}
	if u.Type == 0 || u.Type == 2 {
		if u.Hand, err = lib.ReadVarInt(rr); err != nil {
			return
		}
	}
	return
}

func (k *KeepAliveServerbound) Id() int { return 11 }
func (k *KeepAliveServerbound) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, k.ID); err != nil {
		return
	}
	return
}
func (k *KeepAliveServerbound) Read(rr io.Reader) (err error) {
	if k.ID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (p *Player) Id() int { return 12 }
func (p *Player) Write(ww io.Writer) (err error) {
	if err = lib.WriteBool(ww, p.OnGround); err != nil {
		return
	}
	return
}
func (p *Player) Read(rr io.Reader) (err error) {
	if p.OnGround, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (p *PlayerPosition) Id() int { return 13 }
func (p *PlayerPosition) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp0 := math.Float64bits(p.X)
	tmp[0] = byte(tmp0 >> 56)
	tmp[1] = byte(tmp0 >> 48)
	tmp[2] = byte(tmp0 >> 40)
	tmp[3] = byte(tmp0 >> 32)
	tmp[4] = byte(tmp0 >> 24)
	tmp[5] = byte(tmp0 >> 16)
	tmp[6] = byte(tmp0 >> 8)
	tmp[7] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp1 := math.Float64bits(p.Y)
	tmp[0] = byte(tmp1 >> 56)
	tmp[1] = byte(tmp1 >> 48)
	tmp[2] = byte(tmp1 >> 40)
	tmp[3] = byte(tmp1 >> 32)
	tmp[4] = byte(tmp1 >> 24)
	tmp[5] = byte(tmp1 >> 16)
	tmp[6] = byte(tmp1 >> 8)
	tmp[7] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp2 := math.Float64bits(p.Z)
	tmp[0] = byte(tmp2 >> 56)
	tmp[1] = byte(tmp2 >> 48)
	tmp[2] = byte(tmp2 >> 40)
	tmp[3] = byte(tmp2 >> 32)
	tmp[4] = byte(tmp2 >> 24)
	tmp[5] = byte(tmp2 >> 16)
	tmp[6] = byte(tmp2 >> 8)
	tmp[7] = byte(tmp2 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	if err = lib.WriteBool(ww, p.OnGround); err != nil {
		return
	}
	return
}
func (p *PlayerPosition) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	var tmp0 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp0 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.X = math.Float64frombits(tmp0)
	var tmp1 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp1 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.Y = math.Float64frombits(tmp1)
	var tmp2 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp2 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.Z = math.Float64frombits(tmp2)
	if p.OnGround, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (p *PlayerPositionLook) Id() int { return 14 }
func (p *PlayerPositionLook) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp0 := math.Float64bits(p.X)
	tmp[0] = byte(tmp0 >> 56)
	tmp[1] = byte(tmp0 >> 48)
	tmp[2] = byte(tmp0 >> 40)
	tmp[3] = byte(tmp0 >> 32)
	tmp[4] = byte(tmp0 >> 24)
	tmp[5] = byte(tmp0 >> 16)
	tmp[6] = byte(tmp0 >> 8)
	tmp[7] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp1 := math.Float64bits(p.Y)
	tmp[0] = byte(tmp1 >> 56)
	tmp[1] = byte(tmp1 >> 48)
	tmp[2] = byte(tmp1 >> 40)
	tmp[3] = byte(tmp1 >> 32)
	tmp[4] = byte(tmp1 >> 24)
	tmp[5] = byte(tmp1 >> 16)
	tmp[6] = byte(tmp1 >> 8)
	tmp[7] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp2 := math.Float64bits(p.Z)
	tmp[0] = byte(tmp2 >> 56)
	tmp[1] = byte(tmp2 >> 48)
	tmp[2] = byte(tmp2 >> 40)
	tmp[3] = byte(tmp2 >> 32)
	tmp[4] = byte(tmp2 >> 24)
	tmp[5] = byte(tmp2 >> 16)
	tmp[6] = byte(tmp2 >> 8)
	tmp[7] = byte(tmp2 >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp3 := math.Float32bits(p.Yaw)
	tmp[0] = byte(tmp3 >> 24)
	tmp[1] = byte(tmp3 >> 16)
	tmp[2] = byte(tmp3 >> 8)
	tmp[3] = byte(tmp3 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp4 := math.Float32bits(p.Pitch)
	tmp[0] = byte(tmp4 >> 24)
	tmp[1] = byte(tmp4 >> 16)
	tmp[2] = byte(tmp4 >> 8)
	tmp[3] = byte(tmp4 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	if err = lib.WriteBool(ww, p.OnGround); err != nil {
		return
	}
	return
}
func (p *PlayerPositionLook) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	var tmp0 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp0 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.X = math.Float64frombits(tmp0)
	var tmp1 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp1 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.Y = math.Float64frombits(tmp1)
	var tmp2 uint64
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	tmp2 = (uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56)
	p.Z = math.Float64frombits(tmp2)
	var tmp3 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp3 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.Yaw = math.Float32frombits(tmp3)
	var tmp4 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp4 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.Pitch = math.Float32frombits(tmp4)
	if p.OnGround, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (p *PlayerLook) Id() int { return 15 }
func (p *PlayerLook) Write(ww io.Writer) (err error) {
	var tmp [4]byte
	tmp0 := math.Float32bits(p.Yaw)
	tmp[0] = byte(tmp0 >> 24)
	tmp[1] = byte(tmp0 >> 16)
	tmp[2] = byte(tmp0 >> 8)
	tmp[3] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp1 := math.Float32bits(p.Pitch)
	tmp[0] = byte(tmp1 >> 24)
	tmp[1] = byte(tmp1 >> 16)
	tmp[2] = byte(tmp1 >> 8)
	tmp[3] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	if err = lib.WriteBool(ww, p.OnGround); err != nil {
		return
	}
	return
}
func (p *PlayerLook) Read(rr io.Reader) (err error) {
	var tmp [4]byte
	var tmp0 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.Yaw = math.Float32frombits(tmp0)
	var tmp1 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.Pitch = math.Float32frombits(tmp1)
	if p.OnGround, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (v *VehicleDrive) Id() int { return 16 }
func (v *VehicleDrive) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp[0] = byte(v.X >> 56)
	tmp[1] = byte(v.X >> 48)
	tmp[2] = byte(v.X >> 40)
	tmp[3] = byte(v.X >> 32)
	tmp[4] = byte(v.X >> 24)
	tmp[5] = byte(v.X >> 16)
	tmp[6] = byte(v.X >> 8)
	tmp[7] = byte(v.X >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp[0] = byte(v.Y >> 56)
	tmp[1] = byte(v.Y >> 48)
	tmp[2] = byte(v.Y >> 40)
	tmp[3] = byte(v.Y >> 32)
	tmp[4] = byte(v.Y >> 24)
	tmp[5] = byte(v.Y >> 16)
	tmp[6] = byte(v.Y >> 8)
	tmp[7] = byte(v.Y >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp[0] = byte(v.Z >> 56)
	tmp[1] = byte(v.Z >> 48)
	tmp[2] = byte(v.Z >> 40)
	tmp[3] = byte(v.Z >> 32)
	tmp[4] = byte(v.Z >> 24)
	tmp[5] = byte(v.Z >> 16)
	tmp[6] = byte(v.Z >> 8)
	tmp[7] = byte(v.Z >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp0 := math.Float32bits(v.Yaw)
	tmp[0] = byte(tmp0 >> 24)
	tmp[1] = byte(tmp0 >> 16)
	tmp[2] = byte(tmp0 >> 8)
	tmp[3] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp1 := math.Float32bits(v.Pitch)
	tmp[0] = byte(tmp1 >> 24)
	tmp[1] = byte(tmp1 >> 16)
	tmp[2] = byte(tmp1 >> 8)
	tmp[3] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	return
}
func (v *VehicleDrive) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	v.X = int64((uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56))
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	v.Y = int64((uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56))
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	v.Z = int64((uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56))
	var tmp0 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	v.Yaw = math.Float32frombits(tmp0)
	var tmp1 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	v.Pitch = math.Float32frombits(tmp1)
	return
}

func (s *SteerBoat) Id() int { return 17 }
func (s *SteerBoat) Write(ww io.Writer) (err error) {
	if err = lib.WriteBool(ww, s.Right); err != nil {
		return
	}
	if err = lib.WriteBool(ww, s.Left); err != nil {
		return
	}
	return
}
func (s *SteerBoat) Read(rr io.Reader) (err error) {
	if s.Right, err = lib.ReadBool(rr); err != nil {
		return
	}
	if s.Left, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (c *CraftReceipeRequest) Id() int { return 18 }
func (c *CraftReceipeRequest) Write(ww io.Writer) (err error) {
	var tmp [1]byte
	tmp[0] = byte(c.WindowID >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, c.Receipe); err != nil {
		return
	}
	if err = lib.WriteBool(ww, c.MakeAll); err != nil {
		return
	}
	return
}
func (c *CraftReceipeRequest) Read(rr io.Reader) (err error) {
	var tmp [1]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.WindowID = (byte(tmp[0]) << 0)
	if c.Receipe, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if c.MakeAll, err = lib.ReadBool(rr); err != nil {
		return
	}
	return
}

func (c *ClientAbilities) Id() int { return 19 }
func (c *ClientAbilities) Write(ww io.Writer) (err error) {
	var tmp [4]byte
	tmp[0] = byte(c.Flags >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp0 := math.Float32bits(c.FlyingSpeed)
	tmp[0] = byte(tmp0 >> 24)
	tmp[1] = byte(tmp0 >> 16)
	tmp[2] = byte(tmp0 >> 8)
	tmp[3] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp1 := math.Float32bits(c.WalkingSpeed)
	tmp[0] = byte(tmp1 >> 24)
	tmp[1] = byte(tmp1 >> 16)
	tmp[2] = byte(tmp1 >> 8)
	tmp[3] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	return
}
func (c *ClientAbilities) Read(rr io.Reader) (err error) {
	var tmp [4]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	c.Flags = (byte(tmp[0]) << 0)
	var tmp0 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	c.FlyingSpeed = math.Float32frombits(tmp0)
	var tmp1 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	c.WalkingSpeed = math.Float32frombits(tmp1)
	return
}

func (p *PlayerDigging) Id() int { return 20 }
func (p *PlayerDigging) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp[0] = byte(p.Status >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	tmp[0] = byte(p.Location >> 56)
	tmp[1] = byte(p.Location >> 48)
	tmp[2] = byte(p.Location >> 40)
	tmp[3] = byte(p.Location >> 32)
	tmp[4] = byte(p.Location >> 24)
	tmp[5] = byte(p.Location >> 16)
	tmp[6] = byte(p.Location >> 8)
	tmp[7] = byte(p.Location >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	tmp[0] = byte(p.Face >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	return
}
func (p *PlayerDigging) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	p.Status = (byte(tmp[0]) << 0)
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	p.Location = (lib.Position(tmp[7]) << 0) | (lib.Position(tmp[6]) << 8) | (lib.Position(tmp[5]) << 16) | (lib.Position(tmp[4]) << 24) | (lib.Position(tmp[3]) << 32) | (lib.Position(tmp[2]) << 40) | (lib.Position(tmp[1]) << 48) | (lib.Position(tmp[0]) << 56)
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	p.Face = (byte(tmp[0]) << 0)
	return
}

func (p *PlayerAction) Id() int { return 21 }
func (p *PlayerAction) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, p.EntityID); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, p.ActionID); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, p.JumpBoost); err != nil {
		return
	}
	return
}
func (p *PlayerAction) Read(rr io.Reader) (err error) {
	if p.EntityID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if p.ActionID, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if p.JumpBoost, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (s *SteerVehicle) Id() int { return 22 }
func (s *SteerVehicle) Write(ww io.Writer) (err error) {
	var tmp [4]byte
	tmp0 := math.Float32bits(s.Sideways)
	tmp[0] = byte(tmp0 >> 24)
	tmp[1] = byte(tmp0 >> 16)
	tmp[2] = byte(tmp0 >> 8)
	tmp[3] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp1 := math.Float32bits(s.Forward)
	tmp[0] = byte(tmp1 >> 24)
	tmp[1] = byte(tmp1 >> 16)
	tmp[2] = byte(tmp1 >> 8)
	tmp[3] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp[0] = byte(s.Flags >> 0)
	if _, err = ww.Write(tmp[:1]); err != nil {
		return
	}
	return
}
func (s *SteerVehicle) Read(rr io.Reader) (err error) {
	var tmp [4]byte
	var tmp0 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	s.Sideways = math.Float32frombits(tmp0)
	var tmp1 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	s.Forward = math.Float32frombits(tmp1)
	if _, err = rr.Read(tmp[:1]); err != nil {
		return
	}
	s.Flags = (byte(tmp[0]) << 0)
	return
}

func (c *CraftingBookData) Id() int { return 23 }
func (c *CraftingBookData) Write(ww io.Writer) (err error) {
	var tmp [1]byte
	if err = lib.WriteVarInt(ww, c.Type); err != nil {
		return
	}
	if c.Type == 0 {
		tmp[0] = byte(c.DisplayedReceipe >> 0)
		if _, err = ww.Write(tmp[:1]); err != nil {
			return
		}
	}
	if c.Type == 1 {
		if err = lib.WriteBool(ww, c.CraftingBookOpen); err != nil {
			return
		}
		if err = lib.WriteBool(ww, c.CraftingFilter); err != nil {
			return
		}
	}
	return
}
func (c *CraftingBookData) Read(rr io.Reader) (err error) {
	var tmp [1]byte
	if c.Type, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if c.Type == 0 {
		if _, err = rr.Read(tmp[:1]); err != nil {
			return
		}
		c.DisplayedReceipe = int8((uint8(tmp[0]) << 0))
	}
	if c.Type == 1 {
		if c.CraftingBookOpen, err = lib.ReadBool(rr); err != nil {
			return
		}
		if c.CraftingFilter, err = lib.ReadBool(rr); err != nil {
			return
		}
	}
	return
}

func (r *ResourcePackStatus) Id() int { return 24 }
func (r *ResourcePackStatus) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, r.Result); err != nil {
		return
	}
	return
}
func (r *ResourcePackStatus) Read(rr io.Reader) (err error) {
	if r.Result, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (a *AdvancementTab) Id() int { return 25 }
func (a *AdvancementTab) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, a.Action); err != nil {
		return
	}
	if a.Action == 0 {
		if err = lib.WriteString(ww, a.TabID); err != nil {
			return
		}
	}
	return
}
func (a *AdvancementTab) Read(rr io.Reader) (err error) {
	if a.Action, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if a.Action == 0 {
		if a.TabID, err = lib.ReadString(rr); err != nil {
			return
		}
	}
	return
}

func (h *HeldItemChange) Id() int { return 26 }
func (h *HeldItemChange) Write(ww io.Writer) (err error) {
	var tmp [2]byte
	tmp[0] = byte(h.Slot >> 8)
	tmp[1] = byte(h.Slot >> 0)
	if _, err = ww.Write(tmp[:2]); err != nil {
		return
	}
	return
}
func (h *HeldItemChange) Read(rr io.Reader) (err error) {
	var tmp [2]byte
	if _, err = rr.Read(tmp[:2]); err != nil {
		return
	}
	h.Slot = int16((uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8))
	return
}

func (c *CreativeInventoryAction) Id() int { return 27 }
func (c *CreativeInventoryAction) Write(ww io.Writer) (err error) {
	var tmp [2]byte
	tmp[0] = byte(c.Slot >> 8)
	tmp[1] = byte(c.Slot >> 0)
	if _, err = ww.Write(tmp[:2]); err != nil {
		return
	}
	if err = c.ClickedItem.Serialize(ww); err != nil {
		return
	}
	return
}
func (c *CreativeInventoryAction) Read(rr io.Reader) (err error) {
	var tmp [2]byte
	if _, err = rr.Read(tmp[:2]); err != nil {
		return
	}
	c.Slot = int16((uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8))
	if err = c.ClickedItem.Deserialize(rr); err != nil {
		return
	}
	return
}

func (s *SetSign) Id() int { return 28 }
func (s *SetSign) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp[0] = byte(s.Location >> 56)
	tmp[1] = byte(s.Location >> 48)
	tmp[2] = byte(s.Location >> 40)
	tmp[3] = byte(s.Location >> 32)
	tmp[4] = byte(s.Location >> 24)
	tmp[5] = byte(s.Location >> 16)
	tmp[6] = byte(s.Location >> 8)
	tmp[7] = byte(s.Location >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	if err = lib.WriteString(ww, s.Line1); err != nil {
		return
	}
	if err = lib.WriteString(ww, s.Line2); err != nil {
		return
	}
	if err = lib.WriteString(ww, s.Line3); err != nil {
		return
	}
	if err = lib.WriteString(ww, s.Line4); err != nil {
		return
	}
	return
}
func (s *SetSign) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	s.Location = (lib.Position(tmp[7]) << 0) | (lib.Position(tmp[6]) << 8) | (lib.Position(tmp[5]) << 16) | (lib.Position(tmp[4]) << 24) | (lib.Position(tmp[3]) << 32) | (lib.Position(tmp[2]) << 40) | (lib.Position(tmp[1]) << 48) | (lib.Position(tmp[0]) << 56)
	if s.Line1, err = lib.ReadString(rr); err != nil {
		return
	}
	if s.Line2, err = lib.ReadString(rr); err != nil {
		return
	}
	if s.Line3, err = lib.ReadString(rr); err != nil {
		return
	}
	if s.Line4, err = lib.ReadString(rr); err != nil {
		return
	}
	return
}

func (a *ArmSwing) Id() int { return 29 }
func (a *ArmSwing) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, a.Hand); err != nil {
		return
	}
	return
}
func (a *ArmSwing) Read(rr io.Reader) (err error) {
	if a.Hand, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func (s *SpectateTeleport) Id() int { return 30 }
func (s *SpectateTeleport) Write(ww io.Writer) (err error) {
	if err = s.Target.Serialize(ww); err != nil {
		return
	}
	return
}
func (s *SpectateTeleport) Read(rr io.Reader) (err error) {
	if err = s.Target.Deserialize(rr); err != nil {
		return
	}
	return
}

func (p *PlayerBlockPlacement) Id() int { return 31 }
func (p *PlayerBlockPlacement) Write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp[0] = byte(p.Location >> 56)
	tmp[1] = byte(p.Location >> 48)
	tmp[2] = byte(p.Location >> 40)
	tmp[3] = byte(p.Location >> 32)
	tmp[4] = byte(p.Location >> 24)
	tmp[5] = byte(p.Location >> 16)
	tmp[6] = byte(p.Location >> 8)
	tmp[7] = byte(p.Location >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, p.Face); err != nil {
		return
	}
	if err = lib.WriteVarInt(ww, p.Hand); err != nil {
		return
	}
	tmp0 := math.Float32bits(p.CursorX)
	tmp[0] = byte(tmp0 >> 24)
	tmp[1] = byte(tmp0 >> 16)
	tmp[2] = byte(tmp0 >> 8)
	tmp[3] = byte(tmp0 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp1 := math.Float32bits(p.CursorY)
	tmp[0] = byte(tmp1 >> 24)
	tmp[1] = byte(tmp1 >> 16)
	tmp[2] = byte(tmp1 >> 8)
	tmp[3] = byte(tmp1 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	tmp2 := math.Float32bits(p.CursorZ)
	tmp[0] = byte(tmp2 >> 24)
	tmp[1] = byte(tmp2 >> 16)
	tmp[2] = byte(tmp2 >> 8)
	tmp[3] = byte(tmp2 >> 0)
	if _, err = ww.Write(tmp[:4]); err != nil {
		return
	}
	return
}
func (p *PlayerBlockPlacement) Read(rr io.Reader) (err error) {
	var tmp [8]byte
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	p.Location = (lib.Position(tmp[7]) << 0) | (lib.Position(tmp[6]) << 8) | (lib.Position(tmp[5]) << 16) | (lib.Position(tmp[4]) << 24) | (lib.Position(tmp[3]) << 32) | (lib.Position(tmp[2]) << 40) | (lib.Position(tmp[1]) << 48) | (lib.Position(tmp[0]) << 56)
	if p.Face, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	if p.Hand, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	var tmp0 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp0 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.CursorX = math.Float32frombits(tmp0)
	var tmp1 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp1 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.CursorY = math.Float32frombits(tmp1)
	var tmp2 uint32
	if _, err = rr.Read(tmp[:4]); err != nil {
		return
	}
	tmp2 = (uint32(tmp[3]) << 0) | (uint32(tmp[2]) << 8) | (uint32(tmp[1]) << 16) | (uint32(tmp[0]) << 24)
	p.CursorZ = math.Float32frombits(tmp2)
	return
}

func (u *UseItem) Id() int { return 32 }
func (u *UseItem) Write(ww io.Writer) (err error) {
	if err = lib.WriteVarInt(ww, u.Hand); err != nil {
		return
	}
	return
}
func (u *UseItem) Read(rr io.Reader) (err error) {
	if u.Hand, err = lib.ReadVarInt(rr); err != nil {
		return
	}
	return
}

func init() {
	packets[lib.Play][lib.Serverbound][0] = func() lib.Packet { return &TeleConfirm{} }
	packets[lib.Play][lib.Serverbound][1] = func() lib.Packet { return &TabComplete{} }
	packets[lib.Play][lib.Serverbound][2] = func() lib.Packet { return &ChatMessage{} }
	packets[lib.Play][lib.Serverbound][3] = func() lib.Packet { return &ClientStatus{} }
	packets[lib.Play][lib.Serverbound][4] = func() lib.Packet { return &ClientSettings{} }
	packets[lib.Play][lib.Serverbound][5] = func() lib.Packet { return &ConfirmTransactionServerbound{} }
	packets[lib.Play][lib.Serverbound][6] = func() lib.Packet { return &EnchantItem{} }
	packets[lib.Play][lib.Serverbound][7] = func() lib.Packet { return &ClickWindow{} }
	packets[lib.Play][lib.Serverbound][8] = func() lib.Packet { return &CloseWindow{} }
	packets[lib.Play][lib.Serverbound][9] = func() lib.Packet { return &PluginMessageServerbound{} }
	packets[lib.Play][lib.Serverbound][10] = func() lib.Packet { return &UseEntity{} }
	packets[lib.Play][lib.Serverbound][11] = func() lib.Packet { return &KeepAliveServerbound{} }
	packets[lib.Play][lib.Serverbound][12] = func() lib.Packet { return &Player{} }
	packets[lib.Play][lib.Serverbound][13] = func() lib.Packet { return &PlayerPosition{} }
	packets[lib.Play][lib.Serverbound][14] = func() lib.Packet { return &PlayerPositionLook{} }
	packets[lib.Play][lib.Serverbound][15] = func() lib.Packet { return &PlayerLook{} }
	packets[lib.Play][lib.Serverbound][16] = func() lib.Packet { return &VehicleDrive{} }
	packets[lib.Play][lib.Serverbound][17] = func() lib.Packet { return &SteerBoat{} }
	packets[lib.Play][lib.Serverbound][18] = func() lib.Packet { return &CraftReceipeRequest{} }
	packets[lib.Play][lib.Serverbound][19] = func() lib.Packet { return &ClientAbilities{} }
	packets[lib.Play][lib.Serverbound][20] = func() lib.Packet { return &PlayerDigging{} }
	packets[lib.Play][lib.Serverbound][21] = func() lib.Packet { return &PlayerAction{} }
	packets[lib.Play][lib.Serverbound][22] = func() lib.Packet { return &SteerVehicle{} }
	packets[lib.Play][lib.Serverbound][23] = func() lib.Packet { return &CraftingBookData{} }
	packets[lib.Play][lib.Serverbound][24] = func() lib.Packet { return &ResourcePackStatus{} }
	packets[lib.Play][lib.Serverbound][25] = func() lib.Packet { return &AdvancementTab{} }
	packets[lib.Play][lib.Serverbound][26] = func() lib.Packet { return &HeldItemChange{} }
	packets[lib.Play][lib.Serverbound][27] = func() lib.Packet { return &CreativeInventoryAction{} }
	packets[lib.Play][lib.Serverbound][28] = func() lib.Packet { return &SetSign{} }
	packets[lib.Play][lib.Serverbound][29] = func() lib.Packet { return &ArmSwing{} }
	packets[lib.Play][lib.Serverbound][30] = func() lib.Packet { return &SpectateTeleport{} }
	packets[lib.Play][lib.Serverbound][31] = func() lib.Packet { return &PlayerBlockPlacement{} }
	packets[lib.Play][lib.Serverbound][32] = func() lib.Packet { return &UseItem{} }
}
